[tool.poetry]
name = "weathermate"
version = "0.1.0"
description = ""
authors = ["bluewarn <n5lp97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ttkbootstrap = "^1.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
